version: '3.7'

networks:
  codeFlix-network:
    ipam:
      config:
        - subnet: 172.30.0.0/24

services:
  app:
    build: .
    container_name: 'micro-videos-app'
    command: chmod +x ./home/node/app/entrypoint.sh
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    networks:
      codeFlix-network:
        ipv4_address: 172.30.0.8
